### PR TITLE
Create sqoop.txt

### PR DESCRIPTION
**Pull request by saimanoj1234**
I have  added updated sqoop file

### CODE REVIEW

**Review by saimanoj1234 — COMMENTED** [review]
Okay

**Review by kancharlapavan — COMMENTED** [review]
added file looks perfect.

**Review by kancharlapavan — APPROVED** [review]

**Review by kancharlapavan — CHANGES_REQUESTED** [review]
add some more information regarding scoop.

**Comment by saimanoj1234** [comment]
oaky

**Pull request closed without merging**
